/*+@@file@@----------------------------------------------------------------*//*!
 \file		dssec.h
 \par Description 
            Extension and update of headers for PellesC compiler suite.
 \par Project: 
            PellesC Headers extension
 \date		Created  on Wed Jul  6 17:24:35 2016
 \date		Modified on Wed Jul  6 17:24:35 2016
 \author	frankie
\*//*-@@file@@----------------------------------------------------------------*/

#ifndef _DSSEC_H_
#define _DSSEC_H_
#if __POCC__ >= 500
#pragma once
#endif
#include <aclui.h>
typedef HRESULT (WINAPI *PFNREADOBJECTSECURITY)(LPCWSTR, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR*, LPARAM);
typedef HRESULT (WINAPI *PFNWRITEOBJECTSECURITY)(LPCWSTR, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR, LPARAM);
STDAPI DSCreateISecurityInfoObject(LPCWSTR pwszObjectPath, LPCWSTR pwszObjectClass, DWORD dwFlags, LPSECURITYINFO *ppSI, PFNREADOBJECTSECURITY pfnReadSD, PFNWRITEOBJECTSECURITY pfnWriteSD, LPARAM lpContext);
#define DSSI_READ_ONLY          	0x00000001
#define DSSI_NO_ACCESS_CHECK    	0x00000002
#define DSSI_NO_EDIT_SACL       	0x00000004
#define DSSI_NO_EDIT_OWNER      	0x00000008
#define DSSI_IS_ROOT            	0x00000010
#define DSSI_NO_FILTER          	0x00000020
#define DSSI_NO_READONLY_MESSAGE    0x00000040
STDAPI DSCreateISecurityInfoObjectEx(LPCWSTR pwszObjectPath, LPCWSTR pwszObjectClass, LPCWSTR pwszServer, LPCWSTR pwszUserName, LPCWSTR pwszPassword, DWORD dwFlags, LPSECURITYINFO *ppSI, PFNREADOBJECTSECURITY pfnReadSD, PFNWRITEOBJECTSECURITY pfnWriteSD, LPARAM lpContext);
STDAPI DSCreateSecurityPage(LPCWSTR pwszObjectPath, LPCWSTR pwszObjectClass, DWORD dwFlags, HPROPSHEETPAGE *phPage, PFNREADOBJECTSECURITY pfnReadSD, PFNWRITEOBJECTSECURITY pfnWriteSD, LPARAM lpContext);
STDAPI DSEditSecurity(HWND hwndOwner, LPCWSTR pwszObjectPath, LPCWSTR pwszObjectClass, DWORD dwFlags, LPCWSTR pwszCaption, PFNREADOBJECTSECURITY pfnReadSD, PFNWRITEOBJECTSECURITY pfnWriteSD, LPARAM lpContext);
typedef HRESULT(WINAPI *PFNDSCREATEISECINFO) (LPCWSTR, LPCWSTR, DWORD, LPSECURITYINFO *, PFNREADOBJECTSECURITY, PFNWRITEOBJECTSECURITY, LPARAM);
typedef HRESULT(WINAPI *PFNDSCREATEISECINFOEX) (LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, DWORD, LPSECURITYINFO *, PFNREADOBJECTSECURITY, PFNWRITEOBJECTSECURITY, LPARAM);
typedef HRESULT(WINAPI *PFNDSCREATESECPAGE) (LPCWSTR, LPCWSTR, DWORD, HPROPSHEETPAGE *, PFNREADOBJECTSECURITY, PFNWRITEOBJECTSECURITY, LPARAM);
typedef HRESULT(WINAPI *PFNDSEDITSECURITY) (HWND, LPCWSTR, LPCWSTR, DWORD, LPCWSTR, PFNREADOBJECTSECURITY, PFNWRITEOBJECTSECURITY, LPARAM);
#endif
