/*+@@file@@----------------------------------------------------------------*//*!
 \file		icontactproperties.h
 \par Description 
            Extension and update of headers for PellesC compiler suite.
 \par Project: 
            PellesC Headers extension
 \date		Created  on Sat Jul 16 19:32:37 2016
 \date		Modified on Sat Jul 16 19:32:37 2016
 \author	frankie
\*//*-@@file@@----------------------------------------------------------------*/

#ifndef _CONTACT_PROPERTIES_H_
#define _CONTACT_PROPERTIES_H_
#if __POCC__ >= 500
#pragma once
#endif
#define CONTACTPROP_PUB_NOTES                       L"Notes"
#define CONTACTPROP_PUB_MAILER                      L"Mailer"
#define CONTACTPROP_PUB_PROGID                      L"ProgID"
#define CONTACTPROP_PUB_GENDER                      L"Gender"
#define CONTACTPROP_PUB_GENDER_UNSPECIFIED          L"Unspecified"
#define CONTACTPROP_PUB_GENDER_MALE                 L"Male"
#define CONTACTPROP_PUB_GENDER_FEMALE               L"Female"
#define CONTACTPROP_PUB_CREATIONDATE                L"CreationDate"
#define CONTACTPROP_PUB_L1_CONTACTIDCOLLECTION      L"ContactIDCollection"
#define CONTACTPROP_PUB_L2_CONTACTID                L"/ContactID"
#define CONTACTPROP_PUB_L3_VALUE                    L"/Value"
#define CONTACTPROP_PUB_L1_NAMECOLLECTION           L"NameCollection"
#define CONTACTPROP_PUB_L2_NAME                     L"/Name"
#define CONTACTPROP_PUB_L3_FORMATTEDNAME            L"/FormattedName"
#define CONTACTPROP_PUB_L3_PHONETIC                 L"/Phonetic"
#define CONTACTPROP_PUB_L3_PREFIX                   L"/Prefix"
#define CONTACTPROP_PUB_L3_TITLE                    L"/Title"
#define CONTACTPROP_PUB_L3_GIVENNAME                L"/GivenName"
#define CONTACTPROP_PUB_L3_FAMILYNAME               L"/FamilyName"
#define CONTACTPROP_PUB_L3_MIDDLENAME               L"/MiddleName"
#define CONTACTPROP_PUB_L3_GENERATION               L"/Generation"
#define CONTACTPROP_PUB_L3_SUFFIX                   L"/Suffix"
#define CONTACTPROP_PUB_L3_NICKNAME                 L"/NickName"
#define CONTACTPROP_PUB_L1_POSITIONCOLLECTION       L"PositionCollection"
#define CONTACTPROP_PUB_L2_POSITION                 L"/Position"
#define CONTACTPROP_PUB_L3_ORGANIZATION             L"/Organization"
#define CONTACTPROP_PUB_L3_COMPANY                  L"/Company"
#define CONTACTPROP_PUB_L3_DEPARTMENT               L"/Department"
#define CONTACTPROP_PUB_L3_OFFICE                   L"/Office"
#define CONTACTPROP_PUB_L3_JOB_TITLE                L"/JobTitle"
#define CONTACTPROP_PUB_L3_PROFESSION               L"/Profession"
#define CONTACTPROP_PUB_L3_ROLE                     L"/Role"
#define CONTACTPROP_PUB_L1_PERSONCOLLECTION         L"PersonCollection"
#define CONTACTPROP_PUB_L2_PERSON                   L"/Person"
#define CONTACTPROP_PUB_L3_FORMATTEDNAME            L"/FormattedName"
#define CONTACTPROP_PUB_L3_PERSONID                 L"/PersonID"
#define CONTACTPROP_PUB_L1_DATECOLLECTION           L"DateCollection"
#define CONTACTPROP_PUB_L2_DATE                     L"/Date"
#define CONTACTPROP_PUB_L3_VALUE                    L"/Value"
#define CONTACTPROP_PUB_L1_EMAILADDRESSCOLLECTION   L"EmailAddressCollection"
#define CONTACTPROP_PUB_L2_EMAILADDRESS             L"/EmailAddress"
#define CONTACTPROP_PUB_L3_ADDRESS                  L"/Address"
#define CONTACTPROP_PUB_L3_TYPE                     L"/Type"
#define CONTACTPROP_PUB_L1_CERTIFICATECOLLECTION    L"CertificateCollection"
#define CONTACTPROP_PUB_L2_CERTIFICATE              L"/Certificate"
#define CONTACTPROP_PUB_L3_VALUE                    L"/Value"
#define CONTACTPROP_PUB_L3_THUMBPRINT               L"/ThumbPrint"
#define CONTACTPROP_PUB_L1_PHONENUMBERCOLLECTION    L"PhoneNumberCollection"
#define CONTACTPROP_PUB_L2_PHONENUMBER              L"/PhoneNumber"
#define CONTACTPROP_PUB_L3_NUMBER                   L"/Number"
#define CONTACTPROP_PUB_L3_ALTERNATE                L"/Alternate"
#define CONTACTPROP_PUB_L1_PHYSICALADDRESSCOLLECTION    L"PhysicalAddressCollection"
#define CONTACTPROP_PUB_L2_PHYSICALADDRESS          L"/PhysicalAddress"
#define CONTACTPROP_PUB_L3_ADDRESSLABEL             L"/AddressLabel"
#define CONTACTPROP_PUB_L3_STREET                   L"/Street"
#define CONTACTPROP_PUB_L3_LOCALITY                 L"/Locality"
#define CONTACTPROP_PUB_L3_REGION                   L"/Region"
#define CONTACTPROP_PUB_L3_POSTALCODE               L"/PostalCode"
#define CONTACTPROP_PUB_L3_COUNTRY                  L"/Country"
#define CONTACTPROP_PUB_L3_POBOX                    L"/POBox"
#define CONTACTPROP_PUB_L3_EXTENDEDADDRESS          L"/ExtendedAddress"
#define CONTACTPROP_PUB_L1_IMADDRESSCOLLECTION      L"IMAddressCollection"
#define CONTACTPROP_PUB_L2_IMADDRESSENTRY           L"/IMAddress"
#define CONTACTPROP_PUB_L3_VALUE                    L"/Value"
#define CONTACTPROP_PUB_L3_PROTOCOL                 L"/Protocol"
#define CONTACTPROP_PUB_L1_URLCOLLECTION            L"UrlCollection"
#define CONTACTPROP_PUB_L2_URL                      L"/Url"
#define CONTACTPROP_PUB_L3_VALUE                    L"/Value"
#define CONTACTPROP_PUB_L1_PHOTOCOLLECTION          L"PhotoCollection"
#define CONTACTPROP_PUB_L2_PHOTO                    L"/Photo"
#define CONTACTPROP_PUB_L3_VALUE                    L"/Value"
#define CONTACTPROP_PUB_L3_URL                      L"/Url"
#define CONTACTLABEL_PUB_PREFERRED                  L"Preferred"
#define CONTACTLABEL_PUB_PERSONAL                   L"Personal"
#define CONTACTLABEL_PUB_BUSINESS                   L"Business"
#define CONTACTLABEL_PUB_OTHER                      L"Other"
#define CONTACTLABEL_PUB_VOICE                      L"Voice"
#define CONTACTLABEL_PUB_MOBILE                     L"Mobile"
#define CONTACTLABEL_PUB_PCS                        L"PCS"
#define CONTACTLABEL_PUB_CELLULAR                   L"Cellular"
#define CONTACTLABEL_PUB_CAR                        L"Car"
#define CONTACTLABEL_PUB_PAGER                      L"Pager"
#define CONTACTLABEL_PUB_TTY                        L"TTY"
#define CONTACTLABEL_PUB_FAX                        L"Fax"
#define CONTACTLABEL_PUB_VIDEO                      L"Video"
#define CONTACTLABEL_PUB_MODEM                      L"Modem"
#define CONTACTLABEL_PUB_BBS                        L"BBS"
#define CONTACTLABEL_PUB_ISDN                       L"ISDN"
#define CONTACTLABEL_PUB_AGENT                      L"Agent"
#define CONTACTLABEL_PUB_DOMESTIC                   L"Domestic"
#define CONTACTLABEL_PUB_INTERNATIONAL              L"International"
#define CONTACTLABEL_PUB_POSTAL                     L"Postal"
#define CONTACTLABEL_PUB_PARCEL                     L"Parcel"
#define CONTACTLABEL_PUB_USERTILE                   L"UserTile"
#define CONTACTLABEL_PUB_LOGO                       L"Logo"
#define CONTACTLABEL_WAB_SPOUSE                     L"wab:Spouse"
#define CONTACTLABEL_WAB_CHILD                      L"wab:Child"
#define CONTACTLABEL_WAB_MANAGER                    L"wab:Manager"
#define CONTACTLABEL_WAB_ASSISTANT                  L"wab:Assistant"
#define CONTACTLABEL_WAB_BIRTHDAY                   L"wab:Birthday"
#define CONTACTLABEL_WAB_ANNIVERSARY                L"wab:Anniversary"
#define CONTACTLABEL_WAB_SOCIALNETWORK              L"wab:SocialNetwork"
#define CONTACTLABEL_WAB_SCHOOL                     L"wab:School"
#define CONTACTLABEL_WAB_WISHLIST                   L"wab:WishList"
#endif
