/*+@@file@@----------------------------------------------------------------*//*!
 \file		imapi2fserror.h
 \par Description 
            Extension and update of headers for PellesC compiler suite.
 \par Project: 
            PellesC Headers extension
 \date		Created  on Sat Jul 16 21:30:41 2016
 \date		Modified on Sat Jul 16 21:30:41 2016
 \author	frankie
\*//*-@@file@@----------------------------------------------------------------*/

#ifndef __imapi2fserror_h__
#define __imapi2fserror_h__
#if __POCC__ >= 500
#pragma once
#endif
#ifndef _SKIP_FSI_ERROR_MESSAGE_CODES
#define FACILITY_IMAPI2                  0xAA
#define IMAPI_E_FSI_INTERNAL_ERROR       ((HRESULT)0xC0AAB100L)
#define IMAPI_E_INVALID_PARAM            ((HRESULT)0xC0AAB101L)
#define IMAPI_E_READONLY                 ((HRESULT)0xC0AAB102L)
#define IMAPI_E_NO_OUTPUT                ((HRESULT)0xC0AAB103L)
#define IMAPI_E_INVALID_VOLUME_NAME      ((HRESULT)0xC0AAB104L)
#define IMAPI_E_INVALID_DATE             ((HRESULT)0xC0AAB105L)
#define IMAPI_E_FILE_SYSTEM_NOT_EMPTY    ((HRESULT)0xC0AAB106L)
#define IMAPI_E_NOT_FILE                 ((HRESULT)0xC0AAB108L)
#define IMAPI_E_NOT_DIR                  ((HRESULT)0xC0AAB109L)
#define IMAPI_E_DIR_NOT_EMPTY            ((HRESULT)0xC0AAB10AL)
#define IMAPI_E_NOT_IN_FILE_SYSTEM       ((HRESULT)0xC0AAB10BL)
#define IMAPI_E_INVALID_PATH             ((HRESULT)0xC0AAB110L)
#define IMAPI_E_RESTRICTED_NAME_VIOLATION ((HRESULT)0xC0AAB111L)
#define IMAPI_E_DUP_NAME                 ((HRESULT)0xC0AAB112L)
#define IMAPI_E_NO_UNIQUE_NAME           ((HRESULT)0xC0AAB113L)
#define IMAPI_E_ITEM_NOT_FOUND           ((HRESULT)0xC0AAB118L)
#define IMAPI_E_FILE_NOT_FOUND           ((HRESULT)0xC0AAB119L)
#define IMAPI_E_DIR_NOT_FOUND            ((HRESULT)0xC0AAB11AL)
#define IMAPI_E_IMAGE_SIZE_LIMIT         ((HRESULT)0xC0AAB120L)
#define IMAPI_E_IMAGE_TOO_BIG            ((HRESULT)0xC0AAB121L)
#define IMAPI_E_DATA_STREAM_INCONSISTENCY ((HRESULT)0xC0AAB128L)
#define IMAPI_E_DATA_STREAM_READ_FAILURE ((HRESULT)0xC0AAB129L)
#define IMAPI_E_DATA_STREAM_CREATE_FAILURE ((HRESULT)0xC0AAB12AL)
#define IMAPI_E_DIRECTORY_READ_FAILURE   ((HRESULT)0xC0AAB12BL)
#define IMAPI_E_TOO_MANY_DIRS            ((HRESULT)0xC0AAB130L)
#define IMAPI_E_ISO9660_LEVELS           ((HRESULT)0xC0AAB131L)
#define IMAPI_E_DATA_TOO_BIG             ((HRESULT)0xC0AAB132L)
#define IMAPI_E_INCOMPATIBLE_PREVIOUS_SESSION ((HRESULT)0xC0AAB133L)
#define IMAPI_E_STASHFILE_OPEN_FAILURE   ((HRESULT)0xC0AAB138L)
#define IMAPI_E_STASHFILE_SEEK_FAILURE   ((HRESULT)0xC0AAB139L)
#define IMAPI_E_STASHFILE_WRITE_FAILURE  ((HRESULT)0xC0AAB13AL)
#define IMAPI_E_STASHFILE_READ_FAILURE   ((HRESULT)0xC0AAB13BL)
#define IMAPI_E_INVALID_WORKING_DIRECTORY ((HRESULT)0xC0AAB140L)
#define IMAPI_E_WORKING_DIRECTORY_SPACE  ((HRESULT)0xC0AAB141L)
#define IMAPI_E_STASHFILE_MOVE           ((HRESULT)0xC0AAB142L)
#define IMAPI_E_BOOT_IMAGE_DATA          ((HRESULT)0xC0AAB148L)
#define IMAPI_E_BOOT_OBJECT_CONFLICT     ((HRESULT)0xC0AAB149L)
#define IMAPI_E_BOOT_EMULATION_IMAGE_SIZE_MISMATCH ((HRESULT)0xC0AAB14AL)
#define IMAPI_E_EMPTY_DISC               ((HRESULT)0xC0AAB150L)
#define IMAPI_E_NO_SUPPORTED_FILE_SYSTEM ((HRESULT)0xC0AAB151L)
#define IMAPI_E_FILE_SYSTEM_NOT_FOUND    ((HRESULT)0xC0AAB152L)
#define IMAPI_E_FILE_SYSTEM_READ_CONSISTENCY_ERROR ((HRESULT)0xC0AAB153L)
#define IMAPI_E_FILE_SYSTEM_FEATURE_NOT_SUPPORTED ((HRESULT)0xC0AAB154L)
#define IMAPI_E_IMPORT_TYPE_COLLISION_FILE_EXISTS_AS_DIRECTORY ((HRESULT)0xC0AAB155L)
#define IMAPI_E_IMPORT_SEEK_FAILURE      ((HRESULT)0xC0AAB156L)
#define IMAPI_E_IMPORT_READ_FAILURE      ((HRESULT)0xC0AAB157L)
#define IMAPI_E_DISC_MISMATCH            ((HRESULT)0xC0AAB158L)
#define IMAPI_E_IMPORT_MEDIA_NOT_ALLOWED ((HRESULT)0xC0AAB159L)
#define IMAPI_E_UDF_NOT_WRITE_COMPATIBLE ((HRESULT)0xC0AAB15AL)
#define IMAPI_E_INCOMPATIBLE_MULTISESSION_TYPE ((HRESULT)0xC0AAB15BL)
#define IMAPI_E_NO_COMPATIBLE_MULTISESSION_TYPE ((HRESULT)0xC0AAB15CL)
#define IMAPI_E_MULTISESSION_NOT_SET     ((HRESULT)0xC0AAB15DL)
#define IMAPI_E_IMPORT_TYPE_COLLISION_DIRECTORY_EXISTS_AS_FILE ((HRESULT)0xC0AAB15EL)
#define IMAPI_S_IMAGE_FEATURE_NOT_SUPPORTED ((HRESULT)0x00AAB15FL)
#define IMAPI_E_PROPERTY_NOT_ACCESSIBLE  ((HRESULT)0xC0AAB160L)
#define IMAPI_E_UDF_REVISION_CHANGE_NOT_ALLOWED ((HRESULT)0xC0AAB161L)
#define IMAPI_E_BAD_MULTISESSION_PARAMETER ((HRESULT)0xC0AAB162L)
#define IMAPI_E_FILE_SYSTEM_CHANGE_NOT_ALLOWED ((HRESULT)0xC0AAB163L)
#define IMAPI_E_IMAGEMANAGER_IMAGE_NOT_ALIGNED ((HRESULT)0xC0AAB200L)
#define IMAPI_E_IMAGEMANAGER_NO_VALID_VD_FOUND ((HRESULT)0xC0AAB201L)
#define IMAPI_E_IMAGEMANAGER_NO_IMAGE    ((HRESULT)0xC0AAB202L)
#define IMAPI_E_IMAGEMANAGER_IMAGE_TOO_BIG ((HRESULT)0xC0AAB203L)
#endif
#define IMAPI_ERROR_FIRST	(unsigned int)0xB100
#define IMAPI_ERROR_LAST	(unsigned int)0xB2FF
#define IMAPIError(hr) ((HRESULT_FACILITY(hr) == FACILITY_IMAPI2) && (HRESULT_CODE(hr) <= IMAPI_ERROR_LAST) && (HRESULT_CODE(hr) >= IMAPI_ERROR_FIRST))
#define IMAPI_FSI_ERROR_FIRST	(unsigned int)0xB100
#define IMAPI_FSI_ERROR_LAST	(unsigned int)0xB2FF
#define IMAPIFsiError(hr) ((HRESULT_FACILITY(hr) == FACILITY_IMAPI2) && (HRESULT_CODE(hr) <= IMAPI_FSI_ERROR_LAST) && (HRESULT_CODE(hr) >= IMAPI_FSI_ERROR_FIRST))
#endif
