/*+@@file@@----------------------------------------------------------------*//*!
 \file		sperror.h
 \par Description 
            Extension and update of headers for PellesC compiler suite.
 \par Project: 
            PellesC Headers extension
 \date		Created  on Sat Sep 17 00:57:55 2016
 \date		Modified on Sat Sep 17 00:57:55 2016
 \author	frankie
\*//*-@@file@@----------------------------------------------------------------*/

#ifndef SPError_h
#define SPError_h
#if __POCC__ >= 500
#pragma once
#endif
#ifndef _WINERROR_
#include <winerror.h>
#endif
#define FACILITY_SAPI      FACILITY_ITF
#define SAPI_ERROR_BASE    0x5000
#define MAKE_SAPI_HRESULT(sev, err)    MAKE_HRESULT(sev, FACILITY_SAPI, err)
#define MAKE_SAPI_ERROR(err)           MAKE_SAPI_HRESULT(SEVERITY_ERROR, err + SAPI_ERROR_BASE)
#define MAKE_SAPI_SCODE(scode)         MAKE_SAPI_HRESULT(SEVERITY_SUCCESS, scode + SAPI_ERROR_BASE)
#define SPERR_UNINITIALIZED                                MAKE_SAPI_ERROR(0x001)
#define SPERR_ALREADY_INITIALIZED                          MAKE_SAPI_ERROR(0x002)
#define SPERR_UNSUPPORTED_FORMAT                           MAKE_SAPI_ERROR(0x003)
#define SPERR_INVALID_FLAGS                                MAKE_SAPI_ERROR(0x004)
#define SP_END_OF_STREAM                                   MAKE_SAPI_SCODE(0x005)
#define SPERR_DEVICE_BUSY                                  MAKE_SAPI_ERROR(0x006)
#define SPERR_DEVICE_NOT_SUPPORTED                         MAKE_SAPI_ERROR(0x007)
#define SPERR_DEVICE_NOT_ENABLED                           MAKE_SAPI_ERROR(0x008)
#define SPERR_NO_DRIVER                                    MAKE_SAPI_ERROR(0x009)
#define SPERR_FILE_MUST_BE_UNICODE                         MAKE_SAPI_ERROR(0x00a)
#define SP_INSUFFICIENT_DATA                               MAKE_SAPI_SCODE(0x00b)
#define SPERR_INVALID_PHRASE_ID                            MAKE_SAPI_ERROR(0x00c)
#define SPERR_BUFFER_TOO_SMALL                             MAKE_SAPI_ERROR(0x00d)
#define SPERR_FORMAT_NOT_SPECIFIED                         MAKE_SAPI_ERROR(0x00e)
#define SPERR_AUDIO_STOPPED                                MAKE_SAPI_ERROR(0x00f)
#define SP_AUDIO_PAUSED                                    MAKE_SAPI_SCODE(0x010)
#define SPERR_RULE_NOT_FOUND                               MAKE_SAPI_ERROR(0x011)
#define SPERR_TTS_ENGINE_EXCEPTION                         MAKE_SAPI_ERROR(0x012)
#define SPERR_TTS_NLP_EXCEPTION                            MAKE_SAPI_ERROR(0x013)
#define SPERR_ENGINE_BUSY                                  MAKE_SAPI_ERROR(0x014)
#define SP_AUDIO_CONVERSION_ENABLED                        MAKE_SAPI_SCODE(0x015)
#define SP_NO_HYPOTHESIS_AVAILABLE                         MAKE_SAPI_SCODE(0x016)
#define SPERR_CANT_CREATE                                  MAKE_SAPI_ERROR(0x017)
#define SP_ALREADY_IN_LEX                                  MAKE_SAPI_SCODE(0x018)
#define SPERR_NOT_IN_LEX                                   MAKE_SAPI_ERROR(0x019)
#define SP_LEX_NOTHING_TO_SYNC                             MAKE_SAPI_SCODE(0x01a)
#define SPERR_LEX_VERY_OUT_OF_SYNC                         MAKE_SAPI_ERROR(0x01b)
#define SPERR_UNDEFINED_FORWARD_RULE_REF                   MAKE_SAPI_ERROR(0x01c)
#define SPERR_EMPTY_RULE                                   MAKE_SAPI_ERROR(0x01d)
#define SPERR_GRAMMAR_COMPILER_INTERNAL_ERROR              MAKE_SAPI_ERROR(0x01e)
#define SPERR_RULE_NOT_DYNAMIC                             MAKE_SAPI_ERROR(0x01f)
#define SPERR_DUPLICATE_RULE_NAME                          MAKE_SAPI_ERROR(0x020)
#define SPERR_DUPLICATE_RESOURCE_NAME                      MAKE_SAPI_ERROR(0x021)
#define SPERR_TOO_MANY_GRAMMARS                            MAKE_SAPI_ERROR(0x022)
#define SPERR_CIRCULAR_REFERENCE                           MAKE_SAPI_ERROR(0x023)
#define SPERR_INVALID_IMPORT                               MAKE_SAPI_ERROR(0x024)
#define SPERR_INVALID_WAV_FILE                             MAKE_SAPI_ERROR(0x025)
#define SP_REQUEST_PENDING                                 MAKE_SAPI_SCODE(0x026)
#define SPERR_ALL_WORDS_OPTIONAL                           MAKE_SAPI_ERROR(0x027)
#define SPERR_INSTANCE_CHANGE_INVALID                      MAKE_SAPI_ERROR(0x028)
#define SPERR_RULE_NAME_ID_CONFLICT                        MAKE_SAPI_ERROR(0x029)
#define SPERR_NO_RULES                                     MAKE_SAPI_ERROR(0x02a)
#define SPERR_CIRCULAR_RULE_REF                            MAKE_SAPI_ERROR(0x02b)
#define SP_NO_PARSE_FOUND                                  MAKE_SAPI_SCODE(0x02c)
#define SPERR_INVALID_HANDLE                               MAKE_SAPI_ERROR(0x02d)
#define SPERR_REMOTE_CALL_TIMED_OUT                        MAKE_SAPI_ERROR(0x02e)
#define SPERR_AUDIO_BUFFER_OVERFLOW                        MAKE_SAPI_ERROR(0x02f)
#define SPERR_NO_AUDIO_DATA                                MAKE_SAPI_ERROR(0x030)
#define SPERR_DEAD_ALTERNATE                               MAKE_SAPI_ERROR(0x031)
#define SPERR_HIGH_LOW_CONFIDENCE                          MAKE_SAPI_ERROR(0x032)
#define SPERR_INVALID_FORMAT_STRING                        MAKE_SAPI_ERROR(0x033)
#define SP_UNSUPPORTED_ON_STREAM_INPUT                     MAKE_SAPI_SCODE(0x034)
#define SPERR_APPLEX_READ_ONLY                             MAKE_SAPI_ERROR(0x035)
#define SPERR_NO_TERMINATING_RULE_PATH                     MAKE_SAPI_ERROR(0x036)
#define SP_WORD_EXISTS_WITHOUT_PRONUNCIATION               MAKE_SAPI_SCODE(0x037)
#define SPERR_STREAM_CLOSED                                MAKE_SAPI_ERROR(0x038)
#define SPERR_NO_MORE_ITEMS                                MAKE_SAPI_ERROR(0x039)
#define SPERR_NOT_FOUND                                    MAKE_SAPI_ERROR(0x03a)
#define SPERR_INVALID_AUDIO_STATE                          MAKE_SAPI_ERROR(0x03b)
#define SPERR_GENERIC_MMSYS_ERROR                          MAKE_SAPI_ERROR(0x03c)
#define SPERR_MARSHALER_EXCEPTION                          MAKE_SAPI_ERROR(0x03d)
#define SPERR_NOT_DYNAMIC_GRAMMAR                          MAKE_SAPI_ERROR(0x03e)
#define SPERR_AMBIGUOUS_PROPERTY                           MAKE_SAPI_ERROR(0x03f)
#define SPERR_INVALID_REGISTRY_KEY                         MAKE_SAPI_ERROR(0x040)
#define SPERR_INVALID_TOKEN_ID                             MAKE_SAPI_ERROR(0x041)
#define SPERR_XML_BAD_SYNTAX                               MAKE_SAPI_ERROR(0x042)
#define SPERR_XML_RESOURCE_NOT_FOUND                       MAKE_SAPI_ERROR(0x043)
#define SPERR_TOKEN_IN_USE                                 MAKE_SAPI_ERROR(0x044)
#define SPERR_TOKEN_DELETED                                MAKE_SAPI_ERROR(0x045)
#define SPERR_MULTI_LINGUAL_NOT_SUPPORTED                  MAKE_SAPI_ERROR(0x046)
#define SPERR_EXPORT_DYNAMIC_RULE                          MAKE_SAPI_ERROR(0x047)
#define SPERR_STGF_ERROR                                   MAKE_SAPI_ERROR(0x048)
#define SPERR_WORDFORMAT_ERROR                             MAKE_SAPI_ERROR(0x049)
#define SPERR_STREAM_NOT_ACTIVE                            MAKE_SAPI_ERROR(0x04a)
#define SPERR_ENGINE_RESPONSE_INVALID                      MAKE_SAPI_ERROR(0x04b)
#define SPERR_SR_ENGINE_EXCEPTION                          MAKE_SAPI_ERROR(0x04c)
#define SPERR_STREAM_POS_INVALID                           MAKE_SAPI_ERROR(0x04d)
#define SP_RECOGNIZER_INACTIVE                             MAKE_SAPI_SCODE(0x04e)
#define SPERR_REMOTE_CALL_ON_WRONG_THREAD                  MAKE_SAPI_ERROR(0x04f)
#define SPERR_REMOTE_PROCESS_TERMINATED                    MAKE_SAPI_ERROR(0x050)
#define SPERR_REMOTE_PROCESS_ALREADY_RUNNING               MAKE_SAPI_ERROR(0x051)
#define SPERR_LANGID_MISMATCH                              MAKE_SAPI_ERROR(0x052)
#define SP_PARTIAL_PARSE_FOUND                             MAKE_SAPI_SCODE(0x053)
#define SPERR_NOT_TOPLEVEL_RULE                            MAKE_SAPI_ERROR(0x054)
#define SP_NO_RULE_ACTIVE                                  MAKE_SAPI_SCODE(0x055)
#define SPERR_LEX_REQUIRES_COOKIE                          MAKE_SAPI_ERROR(0x056)
#define SP_STREAM_UNINITIALIZED                            MAKE_SAPI_SCODE(0x057)
#define SPERR_UNSUPPORTED_LANG                             MAKE_SAPI_ERROR(0x059)
#define SPERR_VOICE_PAUSED                                 MAKE_SAPI_ERROR(0x05a)
#define SPERR_AUDIO_BUFFER_UNDERFLOW                       MAKE_SAPI_ERROR(0x05b)
#define SPERR_AUDIO_STOPPED_UNEXPECTEDLY                   MAKE_SAPI_ERROR(0x05c)
#define SPERR_NO_WORD_PRONUNCIATION                        MAKE_SAPI_ERROR(0x05d)
#define SPERR_ALTERNATES_WOULD_BE_INCONSISTENT             MAKE_SAPI_ERROR(0x05e)
#define SPERR_NOT_SUPPORTED_FOR_SHARED_RECOGNIZER          MAKE_SAPI_ERROR(0x05f)
#define SPERR_TIMEOUT                                      MAKE_SAPI_ERROR(0x060)
#define SPERR_REENTER_SYNCHRONIZE                          MAKE_SAPI_ERROR(0x061)
#define SPERR_STATE_WITH_NO_ARCS                           MAKE_SAPI_ERROR(0x062)
#define SPERR_NOT_ACTIVE_SESSION                           MAKE_SAPI_ERROR(0x063)
#define SPERR_ALREADY_DELETED                              MAKE_SAPI_ERROR(0x064)
#define SP_AUDIO_STOPPED                                   MAKE_SAPI_SCODE(0x065)
#define SPERR_RECOXML_GENERATION_FAIL                      MAKE_SAPI_ERROR(0x066)
#define SPERR_SML_GENERATION_FAIL                          MAKE_SAPI_ERROR(0x067)
#define SPERR_NOT_PROMPT_VOICE                             MAKE_SAPI_ERROR(0x068)
#define SPERR_ROOTRULE_ALREADY_DEFINED                     MAKE_SAPI_ERROR(0x069)
#define SPERR_SCRIPT_DISALLOWED                            MAKE_SAPI_ERROR(0x070)
#define SPERR_REMOTE_CALL_TIMED_OUT_START                  MAKE_SAPI_ERROR(0x071)
#define SPERR_REMOTE_CALL_TIMED_OUT_CONNECT                MAKE_SAPI_ERROR(0x072)
#define SPERR_SECMGR_CHANGE_NOT_ALLOWED                    MAKE_SAPI_ERROR(0x073)
#define SP_COMPLETE_BUT_EXTENDABLE                         MAKE_SAPI_SCODE(0x074)
#define SPERR_FAILED_TO_DELETE_FILE                        MAKE_SAPI_ERROR(0x075)
#define SPERR_SHARED_ENGINE_DISABLED                       MAKE_SAPI_ERROR(0x076)
#define SPERR_RECOGNIZER_NOT_FOUND                         MAKE_SAPI_ERROR(0x077)
#define SPERR_AUDIO_NOT_FOUND                              MAKE_SAPI_ERROR(0x078)
#define SPERR_NO_VOWEL                                     MAKE_SAPI_ERROR(0x079)
#define SPERR_UNSUPPORTED_PHONEME                          MAKE_SAPI_ERROR(0x07A)
#define SP_NO_RULES_TO_ACTIVATE                            MAKE_SAPI_SCODE(0x07B)
#define SP_NO_WORDENTRY_NOTIFICATION                       MAKE_SAPI_SCODE(0x07C)
#define SPERR_WORD_NEEDS_NORMALIZATION                     MAKE_SAPI_ERROR(0x07D)
#define SPERR_CANNOT_NORMALIZE                             MAKE_SAPI_ERROR(0x07E)
#define S_LIMIT_REACHED                                    MAKE_SAPI_SCODE(0x07F)
#define S_NOTSUPPORTED                                    MAKE_SAPI_SCODE(0x080)
#define SPERR_TOPIC_NOT_ADAPTABLE                         MAKE_SAPI_ERROR(0x081)
#define SPERR_PHONEME_CONVERSION                          MAKE_SAPI_ERROR(0x082)
#define SPERR_NOT_SUPPORTED_FOR_INPROC_RECOGNIZER         MAKE_SAPI_ERROR(0x083)
#define SPERR_OVERLOAD                                  MAKE_SAPI_ERROR(0x084)
#define SPERR_LEX_INVALID_DATA                          MAKE_SAPI_ERROR(0x085)
#define SPERR_CFG_INVALID_DATA                          MAKE_SAPI_ERROR(0x086)
#define SPERR_LEX_UNEXPECTED_FORMAT                     MAKE_SAPI_ERROR(0x087)
#define SPERR_STRING_TOO_LONG                           MAKE_SAPI_ERROR(0x088)
#define SPERR_STRING_EMPTY                              MAKE_SAPI_ERROR(0x089)
#endif
