#define IDS_APP_TITLE           101
#define IDR_MAINFRAME           128
#define IDD_TUTORIAL1_DIALOG    102
#define IDD_ABOUTBOX            103
#define IDM_ABOUT               104
#define IDM_EXIT                105
#define IDI_TUTORIAL1           107
#define IDI_SMALL               108
#define IDC_TUTORIAL1           109
#define IDI_DIRECTX_ICON        110
#define IDC_MYICON              2
#define IDC_STATIC              -1
